# ktor uses first port as default and the second as override if exists (${?VAR} prefix)

ktor {
    deployment {
        port = 8080
        port = ${?KTOR_PORT}
    }
    application {
        modules = [ com.ReadySetGo.backend.ApplicationKt.module ]
    }
}

database {
    host     = "localhost"
    host     = ${?DB_HOST}
    port     = "5432"
    port     = ${?DB_PORT}
    name     = "readysetgo"
    name     = ${?DB_NAME}
    user     = "rsguser"
    user     = ${?DB_USER}
    password = "rsgpassword"
    password = ${?DB_PASSWORD}
}